apiVersion: v1
kind: Service
metadata:
  name: agente-inteligente-svc
spec:
  type: LoadBalancer   # exp√µe externamente (use NodePort se cluster local)
  selector:
    app: agente-inteligente
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
